SERVICE_NAME: 'Contract API'
PORT: 3000
CONTRACTS_FILE: './contracts.json'
NETWORK:
  URL: 'http://63.33.55.29'
  API_KEY: ''
  WALLET_PRIV_KEY: '0x5b3244868464b97618e1545555f5ce5e443ad09dafb72c560a3d8018e1c2b2b3'
LOG_LEVELS:
  LOG_LEVEL_SYSTEM: 'debug'
  LOG_LEVEL_FILE: 'info'